name: Terraform Module Test with Go

on:
  push:
    branches:
      - develop

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3
        terraform_wrapper: false

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Initialize Go Module
      run: |
        cd test
        go mod init github.com/test/db-module
        go mod tidy

    - name: Run Terraform Tests with Debug Logs
      working-directory: ./test
      env:
        TF_LOG: DEBUG # 디버그 로그를 터미널에 출력
      run: go test -v -timeout 30m